pipeline {
  agent any


  stages {
    stage('Build') {
      steps {
        sh 'echo Building Stage'
      }
    }
  }

  stages {
    stage('Test') {
      steps {
        sh 'echo Testing Stage'
      }
    }
  }
}
