pipeline {
  agent any
  stages {
    stage('Building') {
      steps {
        script {
          sh 'echo  "Building Stage"' 
         }
      }
    }

    stage('Testing') {
      steps {
        script {
          sh 'echo  "Testing Stage"'
        }
      }
    }
  }
}
    
  