---
- name: Ensure MySQL users are present.
  ansible.mysql.mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default(omit) }}"
    plugin: "{{ item.plugin | default(omit) }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ mysql_users }}"
