---
- name: install apache
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: install git
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "git"
    state: present

- name: Ensure web root exists and is writable by ec2-user
  become: true
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: clone a repo
  become_user: ec2-user
  become: true
  become_user: ec2-user
  ansible.builtin.git:
    repo: git@github.com:ilyesbenothmen/tooling.git
    dest: /var/www/html
    key_file: /home/ec2-user/.ssh/id_ed25519
    accept_hostkey: false  
    force: yes

- name: copy html content to one level up
  remote_user: ec2-user
  become: true
  become_user: root
  command: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd, if not started
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  remote_user: ec2-user
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
