---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
   

- name: update LB server
  hosts: lb
  become: yes
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: Create /tmp/test directory and empty file
  hosts: all
  become: true

  tasks:
    - name: Ensure /tmp/test directory exists
      ansible.builtin.file:
        path: /tmp/test
        state: directory
        mode: '0755'

    - name: Ensure /tmp/test/test file exists (empty)
      ansible.builtin.file:
        path: /tmp/test4
        state: touch
        mode: '0644'