---
- name: Include dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Import common configuration
  import_playbook: ../static-assignments/common.yml

- name: Configure webservers
  import_playbook: ../static-assignments/webservers.yml
