---
- name: Include dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Import common configuration
  import_playbook: ../static-assignments/common.yml

- name: Configure webservers
  import_playbook: ../static-assignments/webservers.yml

# Set up MySQL on database servers
- name: Set up MySQL
  hosts: database
  become: true
  vars_files:
    - /home/ubuntu/ansible-config-mgt/secrets/mysql.yml
  roles:
    - mysql

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
